# 1. házi feladat



Az első házi feladat célja a Python és NumPy szoftveres ismeretek felmérése. 

A három feladatcsoportból (A, B, C) egyet-egyet kell mindenkinek megoldania. **Arról, hogy ki melyiket oldja meg, az alábbi linken található lista ad tájékoztatást** Neptun-kód - feladatok listája formában: http://nipgnas1.inf.elte.hu/~vavsaai@nipg.lab/annbsc23_p1_hw1/annbsc23_p1_hw1_assignments.txt

A feladatok megoldásához nem lehet semmilyen egyéb csomagot importálni: kizárólag beépített függvények és adatszerkezetek, valamint az adott feladathoz előre importált csomagok használhatók (2. és 3. feladat: `numpy`). Minden feladat automatikus tesztekkel rendelkezik. A megoldást a feladathoz tartozó **Megoldás** felirat utáni cellába kell írni. A tesztek a **Tesztek** felirat utáni cellában találhatók az egyes feladatokhoz. Ha a teszt futtatásakor az OK felirat megjelenik, _feltehetően_ jó a megoldás, de a 2. és 3. feladatoknál egyéb feltételeket is teljesíteni kell, melyek csak manuálisan lesznek ellenőrzive beadás után. A beadott házi feladatok gépi tanulás alapú plágiumellenőrzésen esnek át. Másolás gyanújának felmerülése esetén mind a másolat(ok), mind az azt/azokat ihlető eredeti megoldások visszautasíthatók.

**Google Colab**

A Google Colab használatáról az alábbi notebook elején találtok leírást: https://colab.research.google.com/drive/1_dti2w4s5D8BVn5QZkPXuLX4-VCeI5xL

**!!! A feladatok megoldását, vagy az arra mutató linkeket bárhol közzétenni tilos !!!**

Elakadás esetén javasolt átnézni a Canvason megosztott segédanyag notebookokat, továbbá a Canvas fórumon kérhető segítség, de másik hallgató által legfeljebb olyan jellegű válasz adható, hogy melyik függvényt érdemes megpróbálni, vagy például egy hasonló példához hogyan kellene a tömböt indexelni. **Akár kérdésben, akár válaszban a megoldás jelentős részét tartalmazó kódrészletet közzétenni tilos.**

**Megoldás és beküldés menete:**

A közzétett, feladatokat tartalmazó Google Colab notebook csak "view" jogosultságokkal van megosztva, így, bár a notebook szerkeszthetőnek látszik, az úgynevezett "Playground" módban nyílik meg, ahol a változtatások nem lesznek mentve. Mindenkinek le kell másolnia a saját Drive-jára a notebook-ot (Google Colab file menü -> Save a copy to Drive): a másolat már maradandóan szerkeszthető és futtatható lesz. **A kész megoldást tartalmazó notebook-ot le kell tölteni**  (Google Colab file menü -> Download .ipynb), **majd a Canvas-ban, a kiírt feladatnál feltölteni.** Link nem adható be, csak az .ipynb fájl. Alternatívaként, Google Colab helyett saját gépen futó Python-nal és Jupyter-rel is szerkeszthetők és futtathatók .ipynb notebookok. **Kérjük a notebook szerkezetét nem módosítani és nem szétszedni külön feladatok szerint!**

**Első határidő:** 2023. április 18., kedd, 23:59.

**Végső határidő:** 2023. május 4., csütörtök, 23:59. - **!!! A végső határidőig mindenkinek az oktatók által elfogadható, beadott megoldással kell rendelkeznie, ezt követően pótlásra és/vagy javításra nincs lehetőség. !!!**

**Pontozás:** A házi feladat helyes megoldása feltétele a jegyszerzésnek. Az, aki az első határidőig teljes, legfeljebb apró hibákat tartalmazó megoldást adott be, 2 extra pontot kap.



## A/1

**BasketballEventsStore**

Egy kosárlabda mérkőzés eseményeit rögzítő osztályt (**BasketballEventsStore**) kell készítened, mely  játékosok neveit és a meccs eseményeit tárolja. A példányosított **BasketballEventsStore** objektumba bejegyezhetők a játékosok nevei, majd az egyes játékosokhoz hozzáadhatók események. Mind a nevek, mind az események szöveges formátumban (string) kerülnek rögzítésre.


Az osztály neve legyen **BasketballEventsStore**. Hat publikus metódusa van:
* ``add_player(playername)``:  eltárolja a `playername` paraméterben átadott string típusú játékosnevet.
* ``add_event(playername, event)``: rögzíti a string típusú `event` eseményt a `playername` nevű játékoshoz. Ha a megadott játékosnév nincs az adatbázisban, váltson ki `UnknownPlayerException`-t.
* ``get_unique_actions() -> [str]``: visszaadja az összes egyedi nevű, tetszőleges játékoshoz rögzített eseményt lista formában.
* ``get_player_names_starting_with(ch) -> [str]``: visszaadja azokat a játékosneveket egy listában, melyek a paraméterül kapott (string típusú) `ch` karakterrel kezdődnek. A függvény ne különböztesse meg a kis- és nagybetűket.
* ``get_total_passes_per_player() -> dict(str, int)``: visszaad egy string kulcsokkal és int értékekkel rendelkező szótárat, melyben minden játékoshoz (kulcs) szerepel, hogy azokhoz hányszor (érték) került rögzítésre a "pass" nevű esemény.
* ``get_players_with_duplicate_actions() -> [str]``: visszaadja az eltárolt játékosok közül azoknak a neveit, akikhez legalább két ugyanolyan nevű esemény lett rögzítve, egy listában.



### Megoldás

In [ ]:
# Your solution ->






### Tesztek

In [ ]:
import unittest

class TestBasketballEventsStore(unittest.TestCase):

    def setUp(self):
        self.stats_store = BasketballEventsStore()

    def test_add_event_unknown_player(self):
        with self.assertRaises(UnknownPlayerException):
            self.stats_store.add_event("Kareem Abdul-Jabbar", "field goal")
        
        try:
            self.stats_store.add_player("Kareem Abdul-Jabbar")
            self.stats_store.add_event("Kareem Abdul-Jabbar", "field goal")
        except UnknownPlayerException:
            self.fail("raised UnknownPlayerException, but player is already added")
        
    def test_get_unique_actions(self):
        self.stats_store.add_player("Kobe Bryant")
        self.assertEqual(len(self.stats_store.get_unique_actions()), 0)
        self.stats_store.add_event("Kobe Bryant", "pass")
        self.stats_store.add_event("Kobe Bryant", "field goal")

        unique_actions = self.stats_store.get_unique_actions()
        self.assertEqual(len(unique_actions), 2)
        self.assertTrue("pass" in unique_actions)
        self.assertTrue("field goal" in unique_actions)

        self.stats_store.add_player("LeBron James")
        self.stats_store.add_event("LeBron James", "pass")
        self.assertEqual(len(self.stats_store.get_unique_actions()), 2)
        self.stats_store.add_event("LeBron James", "tackle")

        unique_actions2 = self.stats_store.get_unique_actions()
        self.assertEqual(len(unique_actions2), 3)
        self.assertTrue("pass" in unique_actions2)
        self.assertTrue("field goal" in unique_actions2)
        self.assertTrue("tackle" in unique_actions2)

    def test_get_player_names_starting_with(self):
        self.stats_store.add_player("Michael Jordan")
        self.assertEqual(self.stats_store.get_player_names_starting_with("M"), ["Michael Jordan"])
        self.assertEqual(self.stats_store.get_player_names_starting_with("m"), ["Michael Jordan"])
        self.stats_store.add_player("Ja Morant")
        self.assertEqual(self.stats_store.get_player_names_starting_with("m"), ["Michael Jordan"])
        self.stats_store.add_player("Mitch Richmond")
        
        m_players = self.stats_store.get_player_names_starting_with("M")
        self.assertTrue("Michael Jordan" in m_players)
        self.assertTrue("Mitch Richmond" in m_players)
        self.assertEqual(len(m_players), 2)

    def test_get_total_passes_per_player(self):
        self.stats_store.add_player("James Harden")
        self.assertEqual(self.stats_store.get_total_passes_per_player(), {"James Harden": 0})
        self.stats_store.add_event("James Harden", "pass")
        self.stats_store.add_event("James Harden", "field goal")
        self.stats_store.add_event("James Harden", "pass")
        self.assertEqual(self.stats_store.get_total_passes_per_player(), {"James Harden": 2})
        self.stats_store.add_player("Russell Westbrook")
        self.stats_store.add_event("Russell Westbrook", "pass")
        self.stats_store.add_event("Russell Westbrook", "tackle")
        self.stats_store.add_event("Russell Westbrook", "free throw")

        passes_per_player = self.stats_store.get_total_passes_per_player()
        self.assertEqual(passes_per_player["Russell Westbrook"], 1)
        self.assertEqual(passes_per_player["James Harden"], 2)

    def test_get_players_with_duplicate_actions(self):
        self.stats_store.add_player("Michael Jordan")
        self.assertEqual(self.stats_store.get_players_with_duplicate_actions(), [])
        self.stats_store.add_event("Michael Jordan", "free throw")
        self.assertEqual(self.stats_store.get_players_with_duplicate_actions(), [])
        self.stats_store.add_player("Shaquille O'Neal")
        self.assertEqual(self.stats_store.get_players_with_duplicate_actions(), [])
        self.stats_store.add_event("Shaquille O'Neal", "tackle")
        self.stats_store.add_event("Shaquille O'Neal", "pass")
        self.stats_store.add_event("Michael Jordan", "pass")
        self.stats_store.add_event("Shaquille O'Neal", "tackle")
        self.assertEqual(self.stats_store.get_players_with_duplicate_actions(), ["Shaquille O'Neal"])
        self.stats_store.add_event("Michael Jordan", "pass")
        self.assertEqual(set(self.stats_store.get_players_with_duplicate_actions()), {"Shaquille O'Neal", "Michael Jordan"})

def suite():
    suite = unittest.TestSuite()
    testfuns = ["test_add_event_unknown_player", "test_get_unique_actions",
                "test_get_player_names_starting_with", "test_get_total_passes_per_player", 
                "test_get_players_with_duplicate_actions"]
    [suite.addTest(TestBasketballEventsStore(fun)) for fun in testfuns]
    return suite

runner = unittest.TextTestRunner(verbosity=2)
runner.run(suite())

## A/2

**BasketballPointsStore**

Egy olyan osztályt kell készítened, mely kosárlabda mérkőzéseken a játékosok pontszerzéseit rögzíti (**BasketballPointsStore**). A példányosított **BasketballPointsStore** objektumba bejegyezhetők a játékosok nevei, majd az egyes játékosokhoz hozzáadhatók azok meccsenkénti pontszerzései.

Az osztály neve legyen **BasketballPointsStore**. Hat publikus metódusa van:
* ``add_player(playername)``: eltárolja a `playername` paraméterben átadott string típusú játékosnevet.
* ``add_match_points(playername, match_points)``: rögzíti a `match_points` paraméterben kapott pontszámokat a `playername` nevű játékoshoz. A `match_points` egy int értékeket tartalmazó tuple, amely az adott játékos egy meccsen szerzett pontjait tárolja. Ha a pontok között az 1, 2 és 3 értéken kívül más szám is szerepel, a függvény váltson ki `InvalidPointsException`-t.
* ``get_players_played_at_least(n) -> [str]``: visszaadja az eltárolt játékosok közül azok neveit, akikről legalább `n` meccsnyi pontszámot, azaz legalább `n` darab pontszám tuple-t rögzítettünk.
* ``get_average_points() -> float``: megadja az összes játékoshoz tárolt összes pont (azaz az 1, 2, 3 értékek) átlagát.
* ``get_player_with_most_points() -> (str, int)``: visszaadja azon játékos nevét, aki a legtöbb pontot szerezte a meccsei alatt összesítve, valamint a meccsek alatt szerzett pontszámok összegét, egy kételemű tuple-ben. Ha több játékos szerzett azonos maximális pontszámot, az egyik ilyen játékos adatait kell visszaadni csak.
* ``get_players_with_many_3s() -> [str]``: visszaadja azon játékosok nevét, akik több 3 pontost dobtak, mint 1 és 2 pontost együttvéve, az összes rögzített meccsüket tekintve.



### Megoldás

In [ ]:
# Your solution ->

class InvalidPointsException(Exception):
  pass

class BasketballPointsStore:

  def __init__(self):
    self.players = {}

  def add_player(self,playername):
    if(playername not in self.players):
      self.players[playername] = []
  
  def add_match_points(self,playername, match_points):
    for n in match_points:
      if n > 3 or n < 1 :
        raise InvalidPointsException 
    if(playername in self.players):
      self.players[playername].append(match_points)
    else:
      self.players[playername] = []
      self.players[playername].append(match_points)

  def get_players_played_at_least(self,n):
    res = []
    for key,value in self.players.items():
      if len(value) >= n:
        res.append(key)
    return res

  def get_average_points(self):
    sum = 0
    cnt = 0
    for value in self.players.values():
      for n in value:
        for x in n:
          cnt+=1
          sum+=x
    if cnt == 0 :
      return 0
    else:
      return sum/cnt

  def get_player_with_most_points(self):
    max = 0
    winner = ""
    for key,val in self.players.items():
      sum = 0
      for n in val:
        for x in n:
          sum+=x
      if max < sum:
        max = sum
        winner = key
    return (winner,max)

  def get_players_with_many_3s(self):
    res = []
    for key,val in self.players.items():
      three = 0
      other = 0
      for n in val:
        for x in n:
          if x == 3 :
            three+=1
          else:
            other+=1
      if three > other:
        res.append(key)
    return res


### Tesztek

In [ ]:
import unittest

class TestBasketballPointsStore(unittest.TestCase):
    def setUp(self):
        self.stats_store = BasketballPointsStore()
    
    def test_add_match_points_invalid_points(self):
        self.stats_store.add_player("Kobe Bryant")
        with self.assertRaises(InvalidPointsException):
            self.stats_store.add_match_points("Kobe Bryant", (1, 2, 4))

        try:
            self.stats_store.add_match_points("Kobe Bryant", (1, 2, 3))
        except InvalidPlayerException:
            self.fail("raised InvalidPointsException, but points are valid")
    
    def test_get_players_played_at_least(self):
        self.assertEqual(self.stats_store.get_players_played_at_least(1), [])
        self.stats_store.add_player("Wilt Chamberlain")
        self.stats_store.add_match_points("Wilt Chamberlain", (1,3,3,3,3))
        self.assertEqual(self.stats_store.get_players_played_at_least(2), []) #['Wilt Chamberlain'] != []
        self.assertEqual(self.stats_store.get_players_played_at_least(1), ["Wilt Chamberlain"])
        self.stats_store.add_player("Larry Bird")
        self.stats_store.add_match_points("Larry Bird", (1,3,1,2,3))
        self.stats_store.add_match_points("Larry Bird", (3,3,2,1))
        self.assertEqual(self.stats_store.get_players_played_at_least(2), ["Larry Bird"])

        at_least_1 = self.stats_store.get_players_played_at_least(1)
        self.assertEqual(len(at_least_1), 2)
        self.assertTrue("Larry Bird" in at_least_1)
        self.assertTrue("Wilt Chamberlain" in at_least_1)
    
    def test_get_average_points(self):
        self.assertAlmostEqual(self.stats_store.get_average_points(), 0)
        self.stats_store.add_player("LeBron James")
        self.stats_store.add_match_points("LeBron James", (3, 2, 1))
        self.assertAlmostEqual(self.stats_store.get_average_points(), 2)
        self.stats_store.add_match_points("LeBron James", (3, 3, 3, 2, 2))
        self.assertAlmostEqual(self.stats_store.get_average_points(), 19/8)
        self.stats_store.add_player("Kareem Abdul-Jabbar")
        self.stats_store.add_match_points("Kareem Abdul-Jabbar", (3, 3, 3, 3, 3,1))
        self.assertAlmostEqual(self.stats_store.get_average_points(), 35/14)
    
    def test_get_player_with_most_points(self):
        self.stats_store.add_player("Kobe Bryant")
        self.stats_store.add_match_points("Kobe Bryant", (1,1,2,3,3))
        self.assertEqual(self.stats_store.get_player_with_most_points(), ("Kobe Bryant", 10))
        self.stats_store.add_player("Michael Jordan")
        self.stats_store.add_match_points("Michael Jordan", (1, 2,3,3))
        self.assertEqual(self.stats_store.get_player_with_most_points(), ("Kobe Bryant", 10))
        self.stats_store.add_match_points("Michael Jordan", (3,3,2))
        self.assertEqual(self.stats_store.get_player_with_most_points(), ("Michael Jordan", 17))
    
    def test_get_players_with_many_3s(self):
        self.assertEqual(self.stats_store.get_players_with_many_3s(), []) #None != []
        self.stats_store.add_player("Stephen Curry")
        self.stats_store.add_match_points("Stephen Curry", (3, 2, 1, 3, 3, 3))
        self.assertEqual(self.stats_store.get_players_with_many_3s(), ["Stephen Curry"])
        self.stats_store.add_match_points("Stephen Curry", (2, 1, 2, 2, 3, 1))
        self.assertEqual(self.stats_store.get_players_with_many_3s(), [])
        self.stats_store.add_match_points("Stephen Curry", (3, 3, 3))
        self.assertEqual(self.stats_store.get_players_with_many_3s(), ["Stephen Curry"])
        self.stats_store.add_player("Reggie Miller")
        self.stats_store.add_match_points("Reggie Miller", (2, 3, 3, 2, 1))
        self.assertEqual(self.stats_store.get_players_with_many_3s(), ["Stephen Curry"])
        self.stats_store.add_match_points("Reggie Miller", (3, 3, 3, 2, 1, 3))

        many_3_players = self.stats_store.get_players_with_many_3s()
        self.assertEqual(len(many_3_players), 2)
        self.assertTrue("Stephen Curry" in many_3_players)
        self.assertTrue("Reggie Miller" in many_3_players)
                         
def suite():
    suite = unittest.TestSuite()
    testfuns = ["test_add_match_points_invalid_points", "test_get_players_played_at_least",
                "test_get_average_points", "test_get_player_with_most_points",
                "test_get_players_with_many_3s"]
    [suite.addTest(TestBasketballPointsStore(fun)) for fun in testfuns]
    return suite

runner = unittest.TextTestRunner(verbosity=2)
runner.run(suite())

test_add_match_points_invalid_points (__main__.TestBasketballPointsStore) ... ok
test_get_players_played_at_least (__main__.TestBasketballPointsStore) ... ok
test_get_average_points (__main__.TestBasketballPointsStore) ... ok
test_get_player_with_most_points (__main__.TestBasketballPointsStore) ... ok
test_get_players_with_many_3s (__main__.TestBasketballPointsStore) ... ok

----------------------------------------------------------------------
Ran 5 tests in 0.019s

OK


<unittest.runner.TextTestResult run=5 errors=0 failures=0>

## A/3

**RPGCharacterKeeper**

Készíts egy osztályt (**RPGCharacterKeeper**), amely szerepjátékokban a játékosok karaktereit és azok különböző képességeihez rendelt módosító pontszámait képes eltárolni. A képességekhez tartozó pontszámok egész számok, lehetnek negatívak is. A példányosított **RPGCharacterKeeper** objektumba bejegyezhetők a karakterek nevei, majd az egyes karakterekhez hozzáadhatók képességek és az azokhoz tartozó módosító pontszámok.

Az osztály neve legyen **RPGCharacterKeeper**. 6 publikus metódusa van:
* ``add_character(name)``: eltárolja a `name` paraméterben átadott string típusú játékos-karakter nevet.
* ``add_stat(name, statname, modifier)``: rögzíti a `name` nevű játékos-karakter `statname` képességéhez a `modifier` pontszámot. Ha a `name` karakter nincs eltárolva az osztályban, `CharacterNotExistsException`-t vált ki.
* ``get_characters_with_long_names()-> [str]``: visszaadja azon játékos-karakterek neveit egy listában, akiknek neve legalább 3, szóközzel elválasztott tagból áll.
* ``get_max_modifiers() -> dict(str, int)``: minden játékos-karakterhez (kulcs) visszaadja az adott karakterhez rendelt legnagyobb módosító pontszámot (érték) egy szótárban. Ha egy képesség módosító pontszáma kisebb, mint 0, adjon vissza 0-t.
* ``get_has_modifier(stat) -> [str]``: Visszaadja azon játékos-karakterek neveinek listáját, akiknek `stat` képességéhez van módosító pontszámuk eltárolva az osztályban.
* ``get_positive_chars() -> [str]``: Visszaadja azon játékos-karakterek neveinek listáját, akikhez több pozitív módosító pontszám van rendelve, mint negatív.

### Megoldás

In [ ]:
# Your solution ->






### Tesztek

In [ ]:
import unittest

class TestRPGCharacterKeeper(unittest.TestCase):
    def setUp(self):
        self.character_keeper = RPGCharacterKeeper()
        self.character_keeper.add_character("Vax'ildan")
    
    def test_add_character(self):
        with self.assertRaises(CharacterNotExistsException):
            self.character_keeper.add_stat("Percy", "Wisdom", +3)

        try:
            self.character_keeper.add_character("Percy")
            self.character_keeper.add_stat("Percy", "Wisdom", +3)
        except InvalidPlayerException:
            self.fail("raised CharacterNotExistsException, but character should exist")
        
    def test_get_characters_with_long_names(self):
        long_names = self.character_keeper.get_characters_with_long_names()
        self.assertEqual(long_names, [])
        
        self.character_keeper.add_character("Percival de Rolo")
        self.character_keeper.add_character("Beauregard")
        long_names = self.character_keeper.get_characters_with_long_names()
        self.assertEqual(long_names, ["Percival de Rolo"])

        self.character_keeper.add_character("Keyleth of the Air Ashari")
        long_names = self.character_keeper.get_characters_with_long_names()
        self.assertEqual(len(long_names), 2)
        self.assertTrue("Percival de Rolo" in long_names)
        self.assertTrue("Keyleth of the Air Ashari" in long_names)

    def test_get_max_modifiers(self):
        max_modifiers = self.character_keeper.get_max_modifiers()
        self.assertEqual(max_modifiers["Vax'ildan"], 0)

        self.character_keeper.add_stat("Vax'ildan", "Strength", -1)
        self.assertEqual(max_modifiers["Vax'ildan"], 0)

        self.character_keeper.add_character("Pike Trickfoot")
        self.character_keeper.add_stat("Pike Trickfoot", "Dexterity", -1)
        self.character_keeper.add_stat("Pike Trickfoot", "Charisma", +2)
        self.character_keeper.add_stat("Pike Trickfoot", "Wisdom", +5)
        max_modifiers = self.character_keeper.get_max_modifiers()
        self.assertEqual(max_modifiers["Vax'ildan"], 0)
        self.assertEqual(max_modifiers["Pike Trickfoot"], 5)

    def test_get_has_modifier(self):
        self.character_keeper.add_stat("Vax'ildan", "Strength", -1)
        has_modifier = self.character_keeper.get_has_modifier("Wisdom")
        self.assertEqual(has_modifier, [])
        has_modifier = self.character_keeper.get_has_modifier("Strength")
        self.assertEqual(has_modifier, ["Vax'ildan"])

        self.character_keeper.add_character("Grog")
        self.character_keeper.add_stat("Grog", "Strength", +6)
        self.character_keeper.add_stat("Grog", "Dexterity", +3)

        self.character_keeper.add_character("Scanlan")
        self.character_keeper.add_stat("Scanlan", "Charisma", +5)

        has_modifier = self.character_keeper.get_has_modifier("Strength")
        self.assertEqual(len(has_modifier), 2)
        self.assertTrue("Vax'ildan" in has_modifier)
        self.assertTrue("Grog" in has_modifier)
        
    def test_get_positive_chars(self):
        positive_chars = self.character_keeper.get_positive_chars()
        self.assertEqual(positive_chars, [])

        self.character_keeper.add_stat("Vax'ildan", "Strength", -1)
        positive_chars = self.character_keeper.get_positive_chars()
        self.assertEqual(positive_chars, [])
        
        self.character_keeper.add_stat("Vax'ildan", "Dexterity", +5)
        self.character_keeper.add_stat("Vax'ildan", "Wisdom", +3)
        positive_chars = self.character_keeper.get_positive_chars()
        self.assertEqual(positive_chars, ["Vax'ildan"])
        
        self.character_keeper.add_character("Vex'ahlia")
        self.character_keeper.add_stat("Vex'ahlia", "Strength", -2)
        self.character_keeper.add_stat("Vex'ahlia", "Charisma", +3)
        positive_chars = self.character_keeper.get_positive_chars()
        self.assertEqual(positive_chars, ["Vax'ildan"])

def suite():
    suite = unittest.TestSuite()
    testfuns = ["test_add_character", "test_get_characters_with_long_names",
                "test_get_max_modifiers", "test_get_has_modifier",
                "test_get_positive_chars"]
    [suite.addTest(TestRPGCharacterKeeper(fun)) for fun in testfuns]
    return suite

runner = unittest.TextTestRunner(verbosity=2)
runner.run(suite())

## B/1

**Hamis felfedezési arány** (False discovery rate)

Multiclass klasszifikáció esetén a mintaelemeink címkéjét k kategória egyikébe becsüljük (például kutya, macska, papagáj, stb.). Ha a becsléshez neuronhálót használunk, tipikusan, mintaelemenként egy-egy k elemű, valószínűségeket tartalmazó vektort kapunk, ahol az egyes valószínűségek a mintaelem egyes kategóriákba tartozásának valószínűségét reprezentálják. Ha szeretnénk ezekből a vektorokból megmondani, hogy egy-egy mintaelem melyik kategóriába tartozik a legnagyobb valószínűség szerint, akkor elég megmondani minden egyes vektorban a maximális elem indexét. Így megkapjuk a becsült kategóriákat.

Klasszifikációs modellek teljesítményének mérésére különböző metrikák léteznek (pl. pontosság - accuracy, precizitás - precision, szenzitivitás - recall, stb.). Az egyes metrikák a teljesítményt csak bizonyos szempontok szerint értékelik, jellemzően, egy modell egyetlen metrikával történő kiértékelése nem ad teljes képet a modell klasszifikációs teljesítményéről.

Ebben a feladatban a **hamis felfedezési arány** (False discovery rate) metrikát kell implementálnod a **multiclass** (kettőnél több kategóriás) **klasszifikáció esetére.** A multiclass hamis felfedezési arány, kategóriák felett átlagolva, azt adja meg, hogy az általunk egy adott kategóriába sorolt elemek közt milyen arányban vannak azok az elemek, melyek valódi címkéje szerint nem a becsült kategóriába tartoznak. Minél nagyobb ez az érték, annál rosszabbak a becsléseink.

Számolásához a bináris (két kategóriás) esetből indulhatunk ki. Ilyenkor az egyik, választott kategóriánk a pozitív kategória, míg a másik a negatív kategória. A bináris hamis felfedezési arány így a következő:

$$ FDR = \dfrac{FP}{FP+VP} $$

ahol VP a valódi pozitívok (azaz ahol a pozitív kategóriát helyesen becsültük) száma, FP pedig a fals pozitívok száma (azaz ahol a pozitív kategóriát helytelenül becsültük). A nevező tehát egyenlő azzal, hogy hány elemet becsültünk a pozitív kategóriába.

Multiclass esetben minden kategóriára számoljuk a fenti arányt úgy, hogy az aktuális kategória a pozitív kategória és mindegyik másik kategória együttvéve a negatív kategória. Az így, kategóriánként kapott FDR értékeknek az átlaga (makro-átlagolás) adja meg a multiclass FDR metrikát.

A feladat, hogy implementáld a `false_discovery_rate` függvényt, ami két paramétert kap:
*   `y_pred` tartalmazza becsült valószínűségeket (ez egy (m, k) alakú tömb, ahol  m  a mintaelemek és  k  a kategóriák száma) 
*   `y_true` tartalmazza az igazi kategóriacímkéket (ez egy (m,) alakú tömb)

A függvény egy számot ad vissza, a kategóriákra egyenként számolt bináris FDR értékek átlagát.

**Kikötés:**  Az implementációt vektoros módon, NumPy-ban, ciklusok és egyéb, annak megfelelő Python konstrukciók használata nélkül kell elkészíteni. További részletek a notebook végén.

### Megoldás

In [ ]:
import numpy as np

# Your solution ->






### Tesztek

In [ ]:
import unittest

class TestFDR(unittest.TestCase):

    def test_two_classes(self):
        two_class_preds = np.array([[0.4, 0.6], [0.8, 0.2], [0.55, 0.45], [0.1, 0.9]])  # [1,0,0,1]
        two_class_labels = np.array([0,0,1,1])
        self.assertAlmostEqual(false_discovery_rate(two_class_preds, two_class_labels), 1./2.)

    def test_three_classes(self):
        three_class_preds = np.array([[0.4, 0.3, 0.3], [0.1, 0.5, 0.4], 
                                     [0.3, 0.2, 0.5], [0.4, 0.25, 0.35]])  # [0,1,2,0]
        three_class_labels = np.array([0, 1, 2, 2])
        self.assertAlmostEqual(false_discovery_rate(three_class_preds, three_class_labels), 1./6.)

    def test_four_classes(self):
        four_class_preds = np.array([[1., 0., 0., 0.], [1., 0., 0., 0.], 
                                     [0., 0., 1., 0.], [0., 0., 1., 0.],
                                     [0., 1., 0., 0.], [0., 0., 0., 1.],
                                     ])  # [0,0,2,2,1,3]
        four_class_labels = np.array([0, 2, 1, 1, 1, 3])
        self.assertAlmostEqual(false_discovery_rate(four_class_preds, four_class_labels), 3./8.)

def suite():
    suite = unittest.TestSuite()
    testfuns = ["test_two_classes", "test_three_classes", "test_four_classes"]
    [suite.addTest(TestFDR(fun)) for fun in testfuns]
    return suite

runner = unittest.TextTestRunner(verbosity=2)
runner.run(suite())

## B/2 

**Hamis mulasztási arány** (False omission rate)

Multiclass klasszifikáció esetén a mintaelemeink címkéjét k kategória egyikébe becsüljük (például kutya, macska, papagáj, stb.). Ha a becsléshez neuronhálót használunk, tipikusan, mintaelemenként egy-egy k elemű, valószínűségeket tartalmazó vektort kapunk, ahol az egyes valószínűségek a mintaelem egyes kategóriákba tartozásának valószínűségét reprezentálják. Ha szeretnénk ezekből a vektorokból megmondani, hogy egy-egy mintaelem melyik kategóriába tartozik a legnagyobb valószínűség szerint, akkor elég megmondani minden egyes vektorban a maximális elem indexét. Így megkapjuk a becsült kategóriákat.

Klasszifikációs modellek teljesítményének mérésére különböző metrikák léteznek (pl. pontosság - accuracy, precizitás - precision, szenzitivitás - recall, stb.). Az egyes metrikák a teljesítményt csak bizonyos szempontok szerint értékelik, jellemzően, egy modell egyetlen metrikával történő kiértékelése nem ad teljes képet a modell klasszifikációs teljesítményéről.

Ebben a feladatban a **hamis mulasztási arány** (False omission rate) metrikát kell implementálnod a **multiclass** (kettőnél több kategóriás) **klasszifikáció esetére.** A multiclass hamis mulasztási arány, kategóriák felett átlagolva, azt adja meg, hogy az általunk egy adott kategóriába nem sorolt elemek közt milyen arányban vannak azok az elemek, melyek valódi címkéje szerint mégis az adott kategóriába tartoznak. Minél nagyobb ez az érték, annál rosszabbak a becsléseink.

Számolásához a bináris (két kategóriás) esetből indulhatunk ki. Ilyenkor az egyik, választott kategóriánk a pozitív kategória, míg a másik a negatív kategória. A bináris hamis mulasztási arány így a következő:

$$ FOR = \dfrac{FN}{FN+VN} $$

ahol VN a valódi negatívok (azaz ahol a negatív kategóriát helyesen becsültük) száma, FN pedig a fals negatívok száma (azaz ahol a negatív kategóriát helytelenül becsültük). A nevező tehát egyenlő azzal, hogy hány elemet becsültünk a negatív kategóriába.

Multiclass esetben minden kategóriára számoljuk a fenti arányt úgy, hogy az aktuális kategória a pozitív kategória és mindegyik másik kategória együttvéve a negatív kategória. Az így, kategóriánként kapott FOR értékeknek az átlaga (makro-átlagolás) adja meg a multiclass FOR metrikát.

A feladat, hogy implementáld a `false_omission_rate` függvényt, ami két paramétert kap:
*   `y_pred` tartalmazza becsült valószínűségeket (ez egy (m, k) alakú tömb, ahol  m  a mintaelemek és  k  a kategóriák száma) 
*   `y_true` tartalmazza az igazi kategóriacímkéket (ez egy (m,) alakú tömb)

A függvény egy számot ad vissza, a kategóriákra egyenként számolt bináris FOR értékek átlagát.

**Kikötés:**  Az implementációt vektoros módon, NumPy-ban, ciklusok és egyéb, annak megfelelő Python konstrukciók használata nélkül kell elkészíteni. További részletek a notebook végén.

### Megoldás

In [ ]:
import numpy as np

# Your solution ->
def false_omission_rate(y_pred,y_true):
  categories = np.unique(y_true)
  converted_pred = np.argmax(y_pred,axis=1)

  fn=np.sum(np.logical_and(np.equal.outer(y_true, categories), np.not_equal.outer(converted_pred, categories)), axis=0)
  vn=np.sum(np.logical_and(np.not_equal.outer(y_true, categories), np.not_equal.outer(converted_pred, categories)), axis=0)
  return np.mean((fn/(fn+vn)))


### Tesztek

In [ ]:
import unittest

class TestFOR(unittest.TestCase):

    def test_two_classes(self):
        two_class_preds = np.array([[0.4, 0.6], [0.8, 0.2], [0.55, 0.45], [0.1, 0.9]])  # [1,0,0,1]
        two_class_labels = np.array([0,0,1,1])
        self.assertAlmostEqual(false_omission_rate(two_class_preds, two_class_labels), 1./2.)

    def test_three_classes(self):
        three_class_preds = np.array([[0.4, 0.3, 0.3], [0.1, 0.5, 0.4], 
                                    [0.3, 0.2, 0.5], [0.4, 0.25, 0.35]])  # [0,1,2,0]
        three_class_labels = np.array([0, 1, 2, 2])
        self.assertAlmostEqual(false_omission_rate(three_class_preds, three_class_labels), 1./9.)

    def test_four_classes(self):
        four_class_preds = np.array([[1., 0., 0., 0.], [1., 0., 0., 0.], 
                                     [0., 0., 1., 0.], [0., 0., 1., 0.],
                                     [0., 1., 0., 0.], [0., 0., 0., 1.],
                                     ])  # [0,0,2,2,1,3]
        four_class_labels = np.array([0, 2, 1, 1, 1, 3])
        self.assertAlmostEqual(false_omission_rate(four_class_preds, four_class_labels), 13./80.)

def suite():
    suite = unittest.TestSuite()
    testfuns = ["test_two_classes", "test_three_classes", "test_four_classes"]
    [suite.addTest(TestFOR(fun)) for fun in testfuns]
    return suite

runner = unittest.TextTestRunner(verbosity=2)
runner.run(suite())

test_two_classes (__main__.TestFOR) ... ok
test_three_classes (__main__.TestFOR) ... ok
test_four_classes (__main__.TestFOR) ... ok

----------------------------------------------------------------------
Ran 3 tests in 0.014s

OK


<unittest.runner.TextTestResult run=3 errors=0 failures=0>

## C/1

**Sudoku**

Készíts egy **SudokuBoard** nevű osztályt, ami a Sudoku táblát reprezentálja! A Sudoku egy 9x9-es tábla, ami kilenc darab 3x3-as blokkra van osztva a sorok és oszlopok mentén. 1-től 9-ig kell elhelyeznünk a számokat úgy, hogy minden sorban, oszlopban, és blokkban a számok egyszer szerepeljenek.

Emellett az osztály a következő tagfüggvényekkel kell, hogy rendelkezzen:

*   `can_place(row_idx, col_idx, num) -> bool` : A függvény egy logikai értéket ad vissza, mely megadja, hogy a Sudoku szabályai szerint elhelyezhető-e a `num` szám a tábla `col_idx`, `row_idx` pozícióján. A sorok és oszlopok indexelése nullától kezdődik.
*   `place(row_idx, col_idx, num) -> bool` : A függvény működése azonos az előző függvényével, azt leszámítva, hogy ha a megadott szám elhelyezhető a tábla megadott pozícióján, akkor ez a függvény el is helyezi azt.

*   `get_num_empty_rows() -> int`: A függvény visszaadja az üres sorok számát.
*   `get_col_idxs_with_missing_num(num) -> ndarray(n_cols_ret,)`: A függvény egy (n_cols_ret,) alakú tömbben visszaadja azoknak az oszlopoknak az indexét, melyekbe még nem került be a `num` szám.
*   `get_block_pos_with_minimal_max() -> (int, int) or None`:  A függvény megadja annak a nemüres 3x3-as blokknak a pozícióját, melyben a legnagyobb szám minimális az egyes nemüres blokkokban elhelyezett legnagyobb számokat tekintve. Ha több ilyen van, az egyiket kell visszadni közülük. Ha minden blokk üres, a függvény `None` értéket adjon vissza! A blokkok pozícióját darabonként két index adja meg. Ha mátrixokként tekintünk a táblára, akkor például a bal alsó blokk pozíciója `(2, 0)` lesz. A függvény a pozíció két indexét egy kételemű tuple-ben adja vissza!
*   `get_num_rows_with_two_nums_present(num1, num2) -> int` : A függvény visszaadja azoknak a soroknak a számát, ahol a `num1` és `num2` számok egyidejűleg jelen vannak. Feltételezhető, hogy a függvény két különböző számot kap argumentumként.

**Kikötés:**  Az implementációt vektoros módon, NumPy-ban, ciklusok és egyéb, annak megfelelő Python konstrukciók használata nélkül kell elkészíteni. További részletek a notebook végén.



### Megoldás

In [267]:
import numpy as np

# Your solution ->

class SudokuBoard:

  def __init__(self):
    self.board = np.zeros((9,9), dtype=np.int8)

  def can_place(self, row_idx, col_idx, num):
    block = self.board[((row_idx // 3)*3):(((row_idx // 3)*3) + 2),((col_idx // 3)*3):(((col_idx // 3)*3) + 2)]
    return not np.any(self.board[row_idx, :] == num) and not np.any(self.board[:, col_idx] == num) and not np.any(block == num) and self.board[row_idx,col_idx] == 0

  def place(self, row_idx, col_idx, num):
    if self.can_place(row_idx,col_idx,num):
      self.board[row_idx,col_idx] = num
      return True
    else : return False

  def get_num_empty_rows(self):
    return (self.board.shape[0] - np.count_nonzero(self.board.sum(axis=1)))

  def get_col_idxs_with_missing_num(self, num):
    return np.where(np.all(self.board != num, axis=0))[0]

  def get_num_rows_with_two_nums_present(self,num1, num2):
    a = np.where(self.board == num1)[0]
    b = np.where(self.board == num2)[0]
    res = np.in1d(a,b)
    res2 = len(res[res == True])
    return res2

  def get_block_pos_with_minimal_max(self):
    if np.all(self.board == 0):
      return None
    else:
      blocks = self.board.reshape(3, 3, 3, 3).transpose(0, 2, 1, 3).reshape(-1, 3, 3)
      max_blocks = np.max(blocks, axis=(1, 2))
      max_blocks[max_blocks == 0] = 126  #ki kell szurni a 0t
      min_idx = np.argmin(max_blocks)
      cols = len(self.board[0])//3
      res = (min_idx // cols, min_idx % cols)
      return res
  

In [269]:
sb = SudokuBoard()
sb.place(3, 3, 9)
sb.get_block_pos_with_minimal_max()# (1, 1)

[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[9 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[126 126 126 126   9 126 126 126 126]
4


(1, 1)

### Tesztek

In [270]:
import unittest

class TestSudoku(unittest.TestCase):
    def test_can_place(self):
        sb = SudokuBoard()
        self.assertTrue(sb.can_place(0, 0, 5))
        self.assertTrue(sb.can_place(8, 0, 5))
        self.assertTrue(sb.can_place(0, 8, 5))
        self.assertTrue(sb.can_place(4, 6, 5))
        self.assertTrue(sb.can_place(8, 8, 5))

        sb.place(3, 3, 5)
        self.assertFalse(sb.can_place(3, 3, 7))
        self.assertFalse(sb.can_place(5, 4, 5))
        self.assertFalse(sb.can_place(7, 3, 5))
        self.assertFalse(sb.can_place(3, 7, 5))
        
        self.assertTrue(sb.can_place(2, 4, 5))
        self.assertTrue(sb.can_place(3, 4, 6))

    def test_place(self):
        sb = SudokuBoard()
        self.assertTrue(sb.place(2, 7, 4))
        self.assertFalse(sb.place(2, 7, 4))
        self.assertFalse(sb.place(2, 7, 5))
        self.assertTrue(sb.place(2, 0, 5))
        self.assertFalse(sb.place(2, 8, 5))

    def test_get_num_empty_rows(self):
        sb = SudokuBoard()
        self.assertEqual(sb.get_num_empty_rows(), 9)
        sb.place(3, 3, 9)
        self.assertEqual(sb.get_num_empty_rows(), 8)
        
        to_insert = [(1, 0, 3), (2, 7, 3), (2, 1, 4)]
        [sb.place(*t) for t in to_insert]
        self.assertEqual(sb.get_num_empty_rows(), 6)
        to_insert = [(5, 8, 4), (8, 0, 4), (3, 7, 8)]
        [sb.place(*t) for t in to_insert]
        self.assertEqual(sb.get_num_empty_rows(), 4)

    def test_get_col_idxs_with_missing_num(self):
        sb = SudokuBoard()
        ret = sb.get_col_idxs_with_missing_num(1)
        self.assertEqual(ret.shape, (9,))
        self.assertEqual(tuple(np.sort(ret)), tuple(range(9)))

        to_insert = [(1, 0, 3), (2, 7, 3), (2, 1, 4), (5, 8, 4), (8, 0, 4), (3, 7, 8)]
        [sb.place(*t) for t in to_insert]
        ret = sb.get_col_idxs_with_missing_num(1)
        self.assertEqual(ret.shape, (9,))
        self.assertEqual(tuple(np.sort(ret)), tuple(range(9)))
        ret = sb.get_col_idxs_with_missing_num(4)
        self.assertEqual(ret.shape, (6,))
        self.assertEqual(tuple(np.sort(ret)), (2,3,4,5,6,7))

        to_insert = [(4, 2, 4), (1, 4, 4), (3, 3, 4), (0, 6, 4), (6, 7, 4)]
        [sb.place(*t) for t in to_insert]
        ret = sb.get_col_idxs_with_missing_num(4)
        self.assertEqual(ret.shape, (1,))
        self.assertEqual(tuple(ret), (5,))

        sb.place(7, 5, 4)
        ret = sb.get_col_idxs_with_missing_num(4)
        self.assertEqual(ret.shape, (0,))

    def test_get_block_pos_with_minimal_max(self):
        sb = SudokuBoard()
        self.assertEqual(sb.get_block_pos_with_minimal_max(), None)
        sb.place(3, 3, 9)
        self.assertEqual(sb.get_block_pos_with_minimal_max(), (1, 1))
        
        to_insert = [(1, 0, 3), (2, 7, 3)]
        [sb.place(*t) for t in to_insert]
        self.assertIn(sb.get_block_pos_with_minimal_max(), [(0, 0), (0, 2)])

        sb.place(2, 1, 4)
        self.assertEqual(sb.get_block_pos_with_minimal_max(), (0, 2))

        to_insert = [(5, 8, 1), (8, 0, 2), (3, 7, 8)]
        [sb.place(*t) for t in to_insert]
        self.assertEqual(sb.get_block_pos_with_minimal_max(), (2, 0))

    def test_get_num_rows_with_two_nums_present(self):
        sb = SudokuBoard()
        self.assertEqual(sb.get_num_rows_with_two_nums_present(5, 7), 0)
        sb.place(3, 3, 9)
        self.assertEqual(sb.get_num_rows_with_two_nums_present(9, 1), 0)
        self.assertEqual(sb.get_num_rows_with_two_nums_present(9, 8), 0)
        sb.place(5, 3, 5)
        self.assertEqual(sb.get_num_rows_with_two_nums_present(9, 5), 0)
        
        to_insert = [(3, 8, 5), (5, 2, 9), (6, 2, 5), (6, 3, 1)]
        [sb.place(*t) for t in to_insert]
        self.assertEqual(sb.get_num_rows_with_two_nums_present(5, 9), 2)
        self.assertEqual(sb.get_num_rows_with_two_nums_present(9, 5), 2)
        self.assertEqual(sb.get_num_rows_with_two_nums_present(9, 1), 0)
        
        to_insert = [(6, 7, 9), (7, 4, 9), (0, 2, 2), (0, 7, 5), (5, 0, 3)]
        [sb.place(*t) for t in to_insert]
        self.assertEqual(sb.get_num_rows_with_two_nums_present(5, 9), 3)
        self.assertEqual(sb.get_num_rows_with_two_nums_present(9, 3), 1)

def suite():
    suite = unittest.TestSuite()
    testfuns = ["test_can_place", "test_place", "test_get_num_empty_rows",
                "test_get_col_idxs_with_missing_num", "test_get_block_pos_with_minimal_max",
                "test_get_num_rows_with_two_nums_present"]
    [suite.addTest(TestSudoku(fun)) for fun in testfuns]
    return suite

runner = unittest.TextTestRunner(verbosity=2)
runner.run(suite())

test_can_place (__main__.TestSudoku) ... ok
test_place (__main__.TestSudoku) ... ok
test_get_num_empty_rows (__main__.TestSudoku) ... ok
test_get_col_idxs_with_missing_num (__main__.TestSudoku) ... ok
test_get_block_pos_with_minimal_max (__main__.TestSudoku) ... ok
test_get_num_rows_with_two_nums_present (__main__.TestSudoku) ... ok

----------------------------------------------------------------------
Ran 6 tests in 0.039s

OK


[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[9 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[126 126 126 126   9 126 126 126 126]
4
[[[0 0 0]
  [3 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 3 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[9 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[  3 126   3 126   9 126 126 126 126]
0
[[[0 0 0]
  [3 0 0]
  [0 4 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 3 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[9 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[  4 126   3 126   9 126 126 126 126]
2
[[[0 0 0]
  [3 0

<unittest.runner.TextTestResult run=6 errors=0 failures=0>

## C/2

**Sudoku**

Készíts egy **SudokuBoard** nevű osztályt, ami a Sudoku táblát reprezentálja! A Sudoku egy 9x9-es tábla, ami kilenc darab 3x3-as blokkra van osztva a sorok és oszlopok mentén. 1-től 9-ig kell elhelyeznünk a számokat úgy, hogy minden sorban, oszlopban, és blokkban a számok egyszer szerepeljenek.

Emellett az osztály a következő tagfüggvényekkel kell, hogy rendelkezzen:

*   `can_place(row_idx, col_idx, num) -> bool` : A függvény egy logikai értéket ad vissza, mely megadja, hogy a Sudoku szabályai szerint elhelyezhető-e a `num` szám a tábla `col_idx`, `row_idx` pozícióján. A sorok és oszlopok indexelése nullától kezdődik.
*   `place(row_idx, col_idx, num) -> bool` : A függvény működése azonos az előző függvényével, azt leszámítva, hogy ha a megadott szám elhelyezhető a tábla megadott pozícióján, akkor ez a függvény el is helyezi azt.

*   `get_num_empty_cols() -> int`: A függvény visszaadja az üres oszlopok számát.
*   `get_block_pos_with_missing_num(num) -> ndarray(n_blocks_ret, 2)`: A függvény egy (n_blocks_ret, 2) alakú tömbben visszaadja azoknak a 3x3-as blokkoknak a pozícióját, melyekbe még nem került be a `num` szám. A blokkok pozícióját darabonként két index adja meg. Ha mátrixokként tekintünk a táblára, akkor például a bal alsó blokk pozíciója `(2, 0)` lesz.
*   `get_row_idx_with_minimal_max() -> int or None`:  A függvény megadja annak a nemüres sornak az indexét, melyben a legnagyobb szám minimális az egyes nemüres sorokban elhelyezett legnagyobb számokat tekintve. Ha több ilyen van, az egyiket kell visszadni közülük. Ha minden sor üres, a függvény `None` értéket adjon vissza!
*   `get_num_cols_with_two_nums_present(num1, num2) -> int` : A függvény visszaadja azoknak az oszlopoknak a számát, ahol a `num1` és `num2` számok egyidejűleg jelen vannak. Feltételezhető, hogy a függvény két különböző számot kap argumentumként.

**Kikötés:**  Az implementációt vektoros módon, NumPy-ban, ciklusok és egyéb, annak megfelelő Python konstrukciók használata nélkül kell elkészíteni. További részletek a notebook végén.



### Megoldás

In [ ]:
import numpy as np

# Your solution ->






### Tesztek

In [ ]:
import unittest

class TestSudoku(unittest.TestCase):
    def test_can_place(self):
        sb = SudokuBoard()
        self.assertTrue(sb.can_place(0, 0, 5))
        self.assertTrue(sb.can_place(8, 0, 5))
        self.assertTrue(sb.can_place(0, 8, 5))
        self.assertTrue(sb.can_place(4, 6, 5))
        self.assertTrue(sb.can_place(8, 8, 5))

        sb.place(3, 3, 5)
        self.assertFalse(sb.can_place(3, 3, 7))
        self.assertFalse(sb.can_place(5, 4, 5))
        self.assertFalse(sb.can_place(7, 3, 5))
        self.assertFalse(sb.can_place(3, 7, 5))
        
        self.assertTrue(sb.can_place(2, 4, 5))
        self.assertTrue(sb.can_place(3, 4, 6))

    def test_place(self):
        sb = SudokuBoard()
        self.assertTrue(sb.place(2, 7, 4))
        self.assertFalse(sb.place(2, 7, 4))
        self.assertFalse(sb.place(2, 7, 5))
        self.assertTrue(sb.place(2, 0, 5))
        self.assertFalse(sb.place(2, 8, 5))

    def test_get_num_empty_cols(self):
        sb = SudokuBoard()
        self.assertEqual(sb.get_num_empty_cols(), 9)
        sb.place(3, 3, 9)
        self.assertEqual(sb.get_num_empty_cols(), 8)
        
        to_insert = [(1, 0, 3), (2, 7, 3), (2, 1, 4)]
        [sb.place(*t) for t in to_insert]
        self.assertEqual(sb.get_num_empty_cols(), 5)
        to_insert = [(5, 8, 4), (8, 0, 4), (3, 7, 8)]
        [sb.place(*t) for t in to_insert]
        self.assertEqual(sb.get_num_empty_cols(), 4)

    def test_get_block_pos_with_missing_num(self):
        sb = SudokuBoard()
        ret = sb.get_block_pos_with_missing_num(1)
        self.assertEqual(ret.shape, (9, 2))
        self.assertGreaterEqual(np.amin(ret), 0)
        self.assertLessEqual(np.amax(ret), 2)
        ret_flat_idxs = np.ravel_multi_index((ret[:,0], ret[:,1]), dims=(3,3))
        self.assertEqual(tuple(np.sort(ret_flat_idxs)), tuple(range(9)))

        to_insert = [(1, 0, 3), (2, 7, 3), (2, 1, 4), (5, 8, 4), (8, 0, 4), (3, 7, 8)]
        [sb.place(*t) for t in to_insert]
        ret = sb.get_block_pos_with_missing_num(1)
        self.assertEqual(ret.shape, (9, 2))
        self.assertGreaterEqual(np.amin(ret), 0)
        self.assertLessEqual(np.amax(ret), 2)
        ret_flat_idxs = np.ravel_multi_index((ret[:,0], ret[:,1]), dims=(3,3))
        self.assertEqual(tuple(np.sort(ret_flat_idxs)), tuple(range(9)))
        ret = sb.get_block_pos_with_missing_num(4)
        self.assertEqual(ret.shape, (6, 2))
        self.assertGreaterEqual(np.amin(ret), 0)
        self.assertLessEqual(np.amax(ret), 2)
        ret_flat_idxs = np.ravel_multi_index((ret[:,0], ret[:,1]), dims=(3,3))
        self.assertEqual(tuple(np.sort(ret_flat_idxs)), (1,2,3,4,7,8))

        to_insert = [(4, 2, 4), (1, 4, 4), (3, 3, 4), (0, 6, 4), (6, 7, 4)]
        [sb.place(*t) for t in to_insert]
        ret = sb.get_block_pos_with_missing_num(4)
        self.assertEqual(ret.shape, (1, 2))
        self.assertGreaterEqual(np.amin(ret), 0)
        self.assertLessEqual(np.amax(ret), 2)
        ret_flat_idxs = np.ravel_multi_index((ret[:,0], ret[:,1]), dims=(3,3))
        self.assertEqual(tuple(ret_flat_idxs), (7,))

        sb.place(7, 5, 4)
        ret = sb.get_block_pos_with_missing_num(4)
        self.assertEqual(ret.shape, (0, 2))

    def test_get_row_idx_with_minimal_max(self):
        sb = SudokuBoard()
        self.assertEqual(sb.get_row_idx_with_minimal_max(), None)
        sb.place(3, 3, 9)
        self.assertEqual(sb.get_row_idx_with_minimal_max(), 3)
        
        to_insert = [(1, 0, 3), (2, 7, 3)]
        [sb.place(*t) for t in to_insert]
        self.assertIn(sb.get_row_idx_with_minimal_max(), [1, 2])

        sb.place(2, 1, 4)
        self.assertEqual(sb.get_row_idx_with_minimal_max(), 1)

        to_insert = [(3, 8, 1), (8, 0, 2), (3, 7, 8)]
        [sb.place(*t) for t in to_insert]
        self.assertEqual(sb.get_row_idx_with_minimal_max(), 8)

    def test_get_num_cols_with_two_nums_present(self):
        sb = SudokuBoard()
        self.assertEqual(sb.get_num_cols_with_two_nums_present(5, 7), 0)
        sb.place(3, 3, 9)
        self.assertEqual(sb.get_num_cols_with_two_nums_present(9, 1), 0)
        self.assertEqual(sb.get_num_cols_with_two_nums_present(9, 8), 0)
        sb.place(5, 3, 5)
        self.assertEqual(sb.get_num_cols_with_two_nums_present(9, 5), 1)
        
        to_insert = [(3, 8, 5), (5, 2, 9), (6, 2, 5), (6, 3, 1)]
        [sb.place(*t) for t in to_insert]
        self.assertEqual(sb.get_num_cols_with_two_nums_present(5, 9), 2)
        self.assertEqual(sb.get_num_cols_with_two_nums_present(9, 5), 2)
        self.assertEqual(sb.get_num_cols_with_two_nums_present(9, 1), 1)
        
        to_insert = [(6, 7, 9), (7, 4, 9), (0, 2, 2), (0, 7, 5), (5, 0, 3)]
        [sb.place(*t) for t in to_insert]
        self.assertEqual(sb.get_num_cols_with_two_nums_present(5, 9), 3)
        self.assertEqual(sb.get_num_cols_with_two_nums_present(9, 3), 0)

def suite():
    suite = unittest.TestSuite()
    testfuns = ["test_can_place", "test_place", "test_get_num_empty_cols",
                "test_get_block_pos_with_missing_num", "test_get_row_idx_with_minimal_max",
                "test_get_num_cols_with_two_nums_present"]
    [suite.addTest(TestSudoku(fun)) for fun in testfuns]
    return suite

runner = unittest.TextTestRunner(verbosity=2)
runner.run(suite())

## C/3

**Sudoku**

Készíts egy **SudokuBoard** nevű osztályt, ami a Sudoku táblát reprezentálja! A Sudoku egy 9x9-es tábla, ami kilenc darab 3x3-as blokkra van osztva a sorok és oszlopok mentén. 1-től 9-ig kell elhelyeznünk a számokat úgy, hogy minden sorban, oszlopban, és blokkban a számok egyszer szerepeljenek.

Emellett az osztály a következő tagfüggvényekkel kell, hogy rendelkezzen:

*   `can_place(row_idx, col_idx, num) -> bool` : A függvény egy logikai értéket ad vissza, mely megadja, hogy a Sudoku szabályai szerint elhelyezhető-e a `num` szám a tábla `col_idx`, `row_idx` pozícióján. A sorok és oszlopok indexelése nullától kezdődik.
*   `place(row_idx, col_idx, num) -> bool` : A függvény működése azonos az előző függvényével, azt leszámítva, hogy ha a megadott szám elhelyezhető a tábla megadott pozícióján, akkor ez a függvény el is helyezi azt.

*   `get_num_empty_blocks() -> int`: A függvény visszaadja az üres 3x3-as blokkoknak a számát.
*   `get_row_idxs_with_missing_num(num) -> ndarray(n_rows_ret,)`: A függvény egy (n_rows_ret,) alakú tömbben visszaadja azoknak a soroknak az indexét, melyekbe még nem került be a `num` szám.
*   `get_col_idx_with_minimal_max() -> int or None`:  A függvény megadja annak a nemüres oszlopnak az indexét, melyben a legnagyobb szám minimális az egyes nemüres oszlopokban elhelyezett legnagyobb számokat tekintve. Ha több ilyen van, az egyiket kell visszadni közülük. Ha minden oszlop üres, a függvény `None` értéket adjon vissza!
*   `get_num_blocks_with_two_nums_present(num1, num2) -> int` : A függvény visszaadja azoknak a 3x3-as blokkoknak a számát, ahol a `num1` és `num2` számok egyidejűleg jelen vannak. Feltételezhető, hogy a függvény két különböző számot kap argumentumként.

**Kikötés:**  Az implementációt vektoros módon, NumPy-ban, ciklusok és egyéb, annak megfelelő Python konstrukciók használata nélkül kell elkészíteni. További részletek a notebook végén.



### Megoldás

In [ ]:
import numpy as np

# Your solution ->






### Tesztek

In [ ]:
import unittest


class TestSudoku(unittest.TestCase):
    def test_can_place(self):
        sb = SudokuBoard()
        self.assertTrue(sb.can_place(0, 0, 5))
        self.assertTrue(sb.can_place(8, 0, 5))
        self.assertTrue(sb.can_place(0, 8, 5))
        self.assertTrue(sb.can_place(4, 6, 5))
        self.assertTrue(sb.can_place(8, 8, 5))

        sb.place(3, 3, 5)
        self.assertFalse(sb.can_place(3, 3, 7))
        self.assertFalse(sb.can_place(5, 4, 5))
        self.assertFalse(sb.can_place(7, 3, 5))
        self.assertFalse(sb.can_place(3, 7, 5))
        
        self.assertTrue(sb.can_place(2, 4, 5))
        self.assertTrue(sb.can_place(3, 4, 6))

    def test_place(self):
        sb = SudokuBoard()
        self.assertTrue(sb.place(2, 7, 4))
        self.assertFalse(sb.place(2, 7, 4))
        self.assertFalse(sb.place(2, 7, 5))
        self.assertTrue(sb.place(2, 0, 5))
        self.assertFalse(sb.place(2, 8, 5))

    def test_get_num_empty_blocks(self):
        sb = SudokuBoard()
        self.assertEqual(sb.get_num_empty_blocks(), 9)
        sb.place(3, 3, 9)
        self.assertEqual(sb.get_num_empty_blocks(), 8)
        
        to_insert = [(1, 0, 3), (2, 7, 3), (2, 1, 4)]
        [sb.place(*t) for t in to_insert]
        self.assertEqual(sb.get_num_empty_blocks(), 6)
        to_insert = [(5, 8, 4), (8, 0, 4), (3, 7, 8)]
        [sb.place(*t) for t in to_insert]
        self.assertEqual(sb.get_num_empty_blocks(), 4)

    def test_get_row_idxs_with_missing_num(self):
        sb = SudokuBoard()
        ret = sb.get_row_idxs_with_missing_num(1)
        self.assertEqual(ret.shape, (9,))
        self.assertEqual(tuple(np.sort(ret)), tuple(range(9)))

        to_insert = [(1, 0, 3), (2, 7, 3), (2, 1, 4), (5, 8, 4), (8, 0, 4), (3, 7, 8)]
        [sb.place(*t) for t in to_insert]
        ret = sb.get_row_idxs_with_missing_num(1)
        self.assertEqual(ret.shape, (9,))
        self.assertEqual(tuple(np.sort(ret)), tuple(range(9)))
        ret = sb.get_row_idxs_with_missing_num(4)
        self.assertEqual(ret.shape, (6,))
        self.assertEqual(tuple(np.sort(ret)), (0,1,3,4,6,7))

        to_insert = [(4, 2, 4), (1, 4, 4), (3, 3, 4), (0, 6, 4), (6, 7, 4)]
        [sb.place(*t) for t in to_insert]
        ret = sb.get_row_idxs_with_missing_num(4)
        self.assertEqual(ret.shape, (1,))
        self.assertEqual(tuple(ret), (7,))

        sb.place(7, 5, 4)
        ret = sb.get_row_idxs_with_missing_num(4)
        self.assertEqual(ret.shape, (0,))

    def test_get_col_idx_with_minimal_max(self):
        sb = SudokuBoard()
        self.assertEqual(sb.get_col_idx_with_minimal_max(), None)
        sb.place(3, 3, 9)
        self.assertEqual(sb.get_col_idx_with_minimal_max(), 3)
        
        to_insert = [(1, 0, 3), (2, 7, 3)]
        [sb.place(*t) for t in to_insert]
        self.assertIn(sb.get_col_idx_with_minimal_max(), [0, 7])

        sb.place(2, 0, 4)
        self.assertEqual(sb.get_col_idx_with_minimal_max(), 7)

        to_insert = [(8, 3, 1), (8, 1, 2), (3, 7, 8)]
        [sb.place(*t) for t in to_insert]
        self.assertEqual(sb.get_col_idx_with_minimal_max(), 1)

    def test_get_num_blocks_with_two_nums_present(self):
        sb = SudokuBoard()
        self.assertEqual(sb.get_num_blocks_with_two_nums_present(5, 7), 0)
        sb.place(3, 3, 9)
        self.assertEqual(sb.get_num_blocks_with_two_nums_present(9, 1), 0)
        self.assertEqual(sb.get_num_blocks_with_two_nums_present(9, 8), 0)
        sb.place(5, 3, 5)
        self.assertEqual(sb.get_num_blocks_with_two_nums_present(9, 5), 1)
        
        to_insert = [(3, 8, 5), (5, 2, 9), (6, 2, 5), (6, 3, 1)]
        [sb.place(*t) for t in to_insert]
        self.assertEqual(sb.get_num_blocks_with_two_nums_present(5, 9), 1)
        self.assertEqual(sb.get_num_blocks_with_two_nums_present(9, 5), 1)
        self.assertEqual(sb.get_num_blocks_with_two_nums_present(9, 1), 0)
        self.assertEqual(sb.get_num_blocks_with_two_nums_present(5, 1), 0)

        to_insert = [(6, 7, 9), (7, 4, 9), (0, 2, 2), (0, 7, 5), (5, 0, 3), (8, 5, 3)]
        [sb.place(*t) for t in to_insert]
        self.assertEqual(sb.get_num_blocks_with_two_nums_present(5, 9), 1)
        self.assertEqual(sb.get_num_blocks_with_two_nums_present(9, 3), 2)
        self.assertEqual(sb.get_num_blocks_with_two_nums_present(5, 2), 0)
        self.assertEqual(sb.get_num_blocks_with_two_nums_present(3, 1), 1)

def suite():
    suite = unittest.TestSuite()
    testfuns = ["test_can_place", "test_place", "test_get_num_empty_blocks",
                "test_get_row_idxs_with_missing_num", "test_get_col_idx_with_minimal_max",
                "test_get_num_blocks_with_two_nums_present"]
    [suite.addTest(TestSudoku(fun)) for fun in testfuns]
    return suite

runner = unittest.TextTestRunner(verbosity=2)
runner.run(suite())

# Kikötések


**Kikötések a 2. és 3. feladathoz:** 
* Nem használhatók Python ciklusok, comprehension-ök és generátorok (azaz tiltott a `for` és a `while` kulcsszavak használata).
* A feladatok nem oldhatók meg rekurzió segítségével.
* Nem használhatók a `map()` és `filter()` beápített függvények.
* Nem használhatók a következő, Python ciklust megvalósító, nem hatékony NumPy függvények: `np.apply_along_axis()`, `np.apply_over_axes()`, `np.vectorize()`, `np.frompyfunc()`.
* Bár a megoldásban nem kell más méretű táblákat kezelni, de **a megoldás módjának skálázhatónak kell lennie a sorok, oszlopok száma és a beléjük írható számjegyek száma szerint**. Azaz, nem elfogadható az a megközelítés, hogy ha kilenc fajta számjegyen szeretnénk végigiterálni, akkor a ciklus használatát úgy kerüljük el, hogy a kilenc számjegyet kilenc külön utasítással kezeljük, hiszen ekkor több sor/oszlop/számjegy esetén több sornyi kódra lenne szükségünk.

**Magyarázat:**

A Python egy interpretált nyelv: az értelmező soronként hajtja végre a kódot, nincs lehetősége optimalizációra, hiszen nem tud előretekinteni. Ebből kifolyólag, minden egyes Python utasítás végrehajtása jelentős overhead-del jár, a tisztán Python-ban írt kód nagyságrendekkel kevésbé hatékonyan futtatható, mint például a gépközeli, fordítás során optimalizált C kód. A NumPy könyvtár lényege, hogy hatékony, előre lefordított programokat biztosít, melyeket a Python kódunkból, függvények formájában tudunk végrehajtani. Mivel minden egyes Python utasítás végrehajtása jelentős időtöbblettel jár, célunk, hogy a NumPy függvényeket egyszerre minél nagyobb méretű adaton tudjuk végrehajtani és a Python kódunk kevés függvényhívást, vagy tetszőleges egyéb utasítást tartalmazzon. 

Például, ha egy ciklusban hívunk NumPy függvényeket és a ciklus több milliószor lefut, az tipikusan jóval kevésbé hatékony, mint ha a Python ciklust megfelelő, egyszerre jóval nagyobb adatmennyiségen dolgozó, vektorizált NumPy hívásokkal ki tudjuk váltani és a szkript lefutása során mindössze néhány, egyszerre nagyobb mennyiségű adaton operáló NumPy hívás fut le.

A ciklusok mellett az azt helyettesítő Python műveletek hatása is hasonló: a list/set/dict comprehension-ök, a `map(), filter()` függvények megvalósítása ugyancsak ciklussal történik. A NumPy tartalmaz néhány további műveletet, melyekről bár azt gondolhatnánk, hogy hatékony végrehajtást eredményeznek (hiszen a NumPy könyvtár adja őket), valójában nem sokkal többek szintaktikus cukornál és gyakorlatilag Python ciklusokat rejtenek el.

Erre példa a NumPy-ban elérhető `np.apply_along_axis()` művelet. Ez, egy általunk megadott, egydimenziós tömbön operáló műveletet ismétel meg egy n dimenziós tömb összes egydimenziós szeletén, majd konkatenálja az eredményt. Bár az `np.apply_along_axis()` függvény látszólag kiváltja a Python ciklust, de ha a benne használt egydimenziós tömbön operáló művelet egy Python kóddal megírt függvény, az `np.apply_along_axis()` egy Python-ban megírt ciklussal lesz ekvivalens, hiszen a belső műveletet is a Python értelmező segítségével futtatjuk.

Amennyiben az `np.apply_along_axis()` függvénynek egy NumPy műveletet adunk meg, általában valamivel hatékonyabb konstrukciót kapunk, azonban a vektorizált programozás lényege, hogy megpróbáljuk minden egyes műveletünket a lehető legnagyobb adatmennyiségen egy lépésben végrehajtani és már maguk a felhasznált műveletek többségében támogatják a vektorizált végrehajtást. Például, ha egy `arr` mátrix soraiban az elemeket szeretnénk rendezni, soronként egymástól függetlenül, az `np.apply_along_axis(func1d=np.sort, axis=1, arr=arr)` utasítás ezt fogja elvégezni nekünk (ugyanúgy, ahogy a ciklusban alkalmazott `arr[i,:] = np.sort(arr[i,:])` utasítás is). Azonban az `np.sort()` függvény már önmagában egy vektorművelet és így képes ugyanazt a műveletet végrehajtani tömbök független szeletein, ezért az `np.sort(arr, axis=1)` utasítás is pontosan ezt fogja tenni. Az `np.apply_along_axis()` függvényhez hasonló `np.vectorize()` függvény dokumentációjában említésre is kerül: _"The vectorize function is provided primarily for convenience, not for performance. The implementation is essentially a for loop."_

